### ISSUE TITLE
Set Interscheme / Giropay Flag

### ISSUE THREAD

**Issue by butu** [hakito/PHP-Stuzza-EPS-BankTransfer#19]
Is there a way to activate giropay via this library. The URL the user gets directed to is 'https://routing.eps.or.at/appl/epsSO/transinit/bankauswahl.html?interscheme=false'. If I manually change interscheme to true, the giropay logo appears and i can also select german banks. But how can I configure this?

Thank you!

**Comment by hakito** [comment]
The Pflichtenheft [V2.6.1](https://eservice.psa.at/de/eps-ueberweisung-dokumentation/send/5-dokumentation/7-pflichtenheft-eps-e-payment-standard-v2-6-1.html) does not mention this get parameter. Actually there is no information about the giropay integration beside the javascript implementation.

So I'd suggest if the change of the parameter works for you that you simply change the url before redirecting the user.
