### ISSUE TITLE
Stuck after TransferInitiatorDetails response

### ISSUE THREAD

**Issue by Shahzad-Adil** [hakito/PHP-Stuzza-EPS-BankTransfer#21]
The TransferInitiatorDetails request response is good. After this response i have redirected to the BankResponseDetails->ClientRedirectUrl. After bank selection, login and authorization; it is redirecting to https://members.psa.at/eservice/epsmsg.php. And it is an empty page. 
What should i do? Whats the error? Please guide.

**Comment by Shahzad-Adil** [comment]
I already did it with test mode and stuzza bank, i dont understand why it is redirecting to the link i mentioned above

**Comment by hakito** [comment]
If it works with test mode its ok.

**Comment by Shahzad-Adil** [comment]
No not working with test mode. i said that i am doing it with test mode and stuzza bank but after verification it is redirecting to the link having empty page

**Comment by hakito** [comment]
Well this URL does not come from my implementation. What do you mean with _verification_? After the user has completed the payment (on the bank page) he will be redirected to your [success (or failure) URL](https://github.com/hakito/PHP-Stuzza-EPS-BankTransfer/blob/master/samples/eps_start.php#L14).

**Comment by Shahzad-Adil** [comment]
I think issue is at my confirmation url, i mean the function on confirmation is not right.

**Comment by Shahzad-Adil** [comment]
I think issue is at my confirmation url, i mean the function on confirmation is not right.

I am working in laravel framework.

The function is;

    ```
public function epsurl(Request $request)
    {
        $paymentConfirmationCallback = function($plainXml, $bankConfirmationDetails)
        {
            // Handle "eps:StatusCode": "OK" or "NOK" or "VOK" or "UNKNOWN"
            if ($bankConfirmationDetails->GetStatusCode() == 'OK')
            {
                // TODO: Do your payment completion handling here
                // You should use $bankConfirmationDetails->GetRemittanceIdentifier();
                $bankConfirmationDetails->GetRemittanceIdentifier();
            }

            // True is expected to be returned, otherwise the Scheme Operator will be informed that the server could not accept the payment confirmation
            return true;
        };

        $soCommunicator = new eps_bank_transfer\SoCommunicator();
        $soCommunicator->HandleConfirmationUrl(
          $paymentConfirmationCallback,
          null,                 // Optional: a callback function which is called in case of Vitality-Check
          'php://input',        // This needs to be the raw post data received by the server. Change this only if you want to test this function with simulation data.
          'php://output'        // This needs to be the raw output stream which is sent to the Scheme Operator. Change this only if you want to test this function with simulation data.
        );

    }
```

**Comment by Shahzad-Adil** [comment]
_**Please Help.**_

**Comment by Shahzad-Adil** [comment]
Can you please describe this function in detail?

**Comment by hakito** [comment]
First you declare a callback function, that will be called from the SoCommunicator. This callback function will receive a parsed object of the BankConfirmationDetails XML that is sent as plain text from the scheme operator to your server.

That's why the HandleConfirmationUrl gets php://input and php://output as arguments. I don't know what laravel does before. If it already consumes the php://input you have to forward it properly to the HandleConfirmationUrl.

The HandleConfirmationUrl also directly writes to the output stream. So again if the framework should be blocked writing to the output stream as well.

**Comment by hakito** [comment]
I don't know if this gives you the right direction but I also wrote a [plugin for the CakePHP framework](https://github.com/hakito/CakePHP-EpsBankTransfer-Plugin). But maybe it shows what you have to consider when you're adapting it to laravel.

**Comment by Shahzad-Adil** [comment]
Thanks alot.
just tell me is the confirmation request sending the php file to the ConfirmationUrl ?

**Comment by hakito** [comment]
No, sending the contents of a script file would be a huge security issue and makes also no sense. The whole communication between client and server is based on an XML protocol.
